<div class="isolate bg-white px-6 py-32 lg:px-8">
    <div class="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]" aria-hidden="true">
        <div class="relative left-1/2 -z-10 aspect-[1155/678] w-[36.125rem] max-w-none -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#5cc2e1] to-[#1440ff] opacity-30 sm:left-[calc(50%-40rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
    <div class="relative flex items-top justify-center sm:items-center sm:pt-0">
        <div class="max-w-6xl mx-auto sm:px-6 lg:px-8">
            <div class="mt-8 overflow-hidden">
                <div class="grid grid-cols-1 md:grid-cols-2">
                    <div class="p-6 mr-2 sm:rounded-lg">
                        <h1 class="text-4xl sm:text-5xl text-gray-800 font-extrabold tracking-tight">
                            Get in touch
                        </h1>
                        <p class="text-normal text-lg sm:text-2xl font-medium text-gray-600 mt-2">
                            Fill in the form to start a conversation
                        </p>

                        <div class="flex items-center mt-4 text-gray-600">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24" class="w-8 h-8 text-gray-500">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                            </svg>
                            <div class="ml-4 text-md tracking-wide font-semibold w-40">
                                +44 1234567890
                            </div>
                        </div>

                        <div class="flex items-center mt-2 text-gray-600">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24" class="w-8 h-8 text-gray-500">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                            </svg>
                            <div class="ml-4 text-md tracking-wide font-semibold w-40">
                                info@acme.org
                            </div>
                        </div>
                    </div>

                    <form class="p-6 flex flex-col justify-center" id="sendForm">
                        <div class="flex flex-col">
                            <label for="name" class="hidden">Full Name</label>
                            <input type="name" name="name" id="name" placeholder="Full Name" class="w-100 mt-2 py-3 px-3 rounded-lg bg-white border border-gray-400 dark:border-gray-700 text-gray-800 font-semibold focus:border-indigo-500 focus:outline-none" required>
                        </div>

                        <div class="flex flex-col mt-2">
                            <label for="email" class="hidden">Email</label>
                            <input type="email" name="email" id="email" placeholder="Email" class="w-100 mt-2 py-3 px-3 rounded-lg bg-white border border-gray-400 dark:border-gray-700 text-gray-800 font-semibold focus:border-indigo-500 focus:outline-none" required>
                        </div>

                        <div class="flex flex-col mt-2">
                            <label for="tel" class="hidden">Message</label>
                            <textarea type="text" name="message" id="message" placeholder="Message" class="w-100 mt-2 py-3 px-3 rounded-lg bg-white border border-gray-400 dark:border-gray-700 text-gray-800 font-semibold focus:border-indigo-500 focus:outline-none h-32" required></textarea>
                        </div>

                        <button type="submit" class="md:w-32 bg-[#1440ff] text-white font-bold py-3 px-6 rounded-lg mt-3 hover:bg-blue-800 transition ease-in-out duration-300">
                            Submit
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="assets/vendor/sweetalert2.min.js"></script>
<script>
    const sendForm = document.querySelector('#sendForm');
    sendForm.addEventListener("submit", (e) => {
        e.preventDefault();

        // handle submit
        const emailInput = document.querySelector('#email');
        const nameInput = document.querySelector('#name');
        const messageInput = document.querySelector('#message');

        const email = emailInput.value;
        const name = nameInput.value;
        const msg = messageInput.value;

        let data = new FormData(sendForm);

        fetch("<?= DOMAIN ?>/post/email", {
                method: "POST",
                body: data
            })

            // (C) RETURN SERVER RESPONSE AS TEXT
            .then(res => {
                if (res.status != 200) {
                    throw new Error("Bad Server Response");
                }
                return res.text();
            })

            // (D) SERVER RESPONSE
            .then(res => {
                result = JSON.parse(res);
                if (result.is_errors === 1) {
                    console.log(result.info);
                    Swal.fire({
                        icon: 'error',
                        title: 'Failed to Send Message',
                        text: 'Something went wrong!, please try again.'
                    })
                } else {
                    emailInput.value = '';
                    nameInput.value = '';
                    messageInput.value = '';
                    Swal.fire(
                        'Message Successfuly Sent',
                        'We have received your message and will reply as soon as possible. Thank you.',
                        'success'
                    );
                }
            })

            // (E) HANDLE ERRORS - OPTIONAL
            .catch(err => {
                console.error(err);
                Swal.fire({
                    icon: 'error',
                    title: 'Unable to Send Message',
                    text: 'We are having issue on our server, please try again lates'
                })
            });
    });
</script>