<style>
    .flickity-viewport {
        height: 500px !important;
    }

    .video-docker video {
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    .video-docker::after {
        content: "";
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        background: rgba(0, 0, 0, 0.6);
        z-index: 1;
    }

    .video-content {
        z-index: 2;
    }
</style>
<section class="relative h-screen flex flex-col items-center justify-center text-center text-white py-0 px-3">
    <div class="row_bg">
        <!--
        <div class="absolute top-0 left-0 w-full h-full overflow-hidden">
            <video class="min-w-full min-h-full absolute object-cover" src="storage/home_playback.mp4" type="video/mp4" autoplay muted loop></video>
        </div>
        -->
        <div class="content-video-bg slider">
            <div class="tp-banner-container" style="overflow: visible;">
                <div class="tp-banner-slider revslider-initialised tp-simpleresponsive" id="revslider-845" style="margin-top: 0px; margin-bottom: 0px; height: 700px; opacity: 1;">
                    <ul class="tp-revslider-mainul" style="visibility: visible; display: block; overflow: hidden; width: 1862px; height: 100%; max-height: none; left: 0px;">
                        <li data-masterspeed="10" data-transition="" class="tp-revslider-slidesli active-revslide" style="width: 100%; height: 100%; overflow: hidden; z-index: 20; visibility: inherit; opacity: 1;">
                            <div class="sl-title-container">
                                <div class="sl-title-top"></div>
                                <div class="sl-title"></div>
                                <div class="sl-title-bot"><span></span></div>
                            </div>
                        </li>
                    </ul>
                    <div class="tp-loader spinner0" style="display: none;">
                        <div class="dot1"></div>
                        <div class="dot2"></div>
                        <div class="bounce1"></div>
                        <div class="bounce2"></div>
                        <div class="bounce3"></div>
                    </div>
                    <div class="tp-bannertimer" style="visibility: hidden; width: 0%;"></div>
                    <div class="tp-leftarrow tparrows" style="top: 50%; transform: matrix(1, 0, 0, 1, 0, -20); left: 0px; visibility: hidden; opacity: 0;"></div>
                    <div class="tp-rightarrow tparrows" style="top: 50%; transform: matrix(1, 0, 0, 1, -40, -20); left: 100%; visibility: hidden; opacity: 0;"></div>
                </div>
            </div>
        </div>
        <div class="slider-info-wrap clearfix">
            <div class="slider-info-content">
                <div class="slider-info-item">
                    <div class="info-item-media">
                        <img src="assets/img/luxury-classic-modern-bedroom-suite-hotel.jpg" data-at2x="assets/img/luxury-classic-modern-bedroom-suite-hotel.jpg" alt="">
                        <div class="info-item-text">
                            <div class="info-price font-4"><span></span></div>
                            <div class="info-temp font-4"><span></span></div>
                            <p class="info-text"></p>
                        </div>
                    </div>
                    <div class="info-item-content">
                        <div class="main-title">
                            <h3 class="title">
                                <span class="font-4">Hotel</span> Reservations
                            </h3>
                            <div class="price"><span></span></div>
                            <a href="#" class="button">Details</a>
                        </div>
                    </div>
                </div>
                <div class="slider-info-item">
                    <div class="info-item-media">
                        <img src="assets/img/stylish-elegant-woman-car-salon.jpg" data-at2x="assets/img/stylish-elegant-woman-car-salon.jpg" alt="">
                        <div class="info-item-text">
                            <div class="info-price font-4"><span></span></div>
                            <div class="info-temp font-4"><span></span></div>
                            <p class="info-text"></p>
                        </div>
                    </div>
                    <div class="info-item-content">
                        <div class="main-title">
                            <h3 class="title"><span class="font-4">Car</span> Booking</h3>
                            <div class="price"><span></span></div>
                            <a href="#" class="button">Details</a>
                        </div>
                    </div>
                </div>
                <div class="slider-info-item">
                    <div class="info-item-media">
                        <img src="assets/img/james-bond-islands-in-thailand-2022-11-10-17-55-09-utc.jpg" data-at2x="assets/img/james-bond-islands-in-thailand-2022-11-10-17-55-09-utc.jpg" alt="">
                        <div class="info-item-text">
                            <div class="info-price font-4"><span></span></div>
                            <div class="info-temp font-4"><span></span></div>
                            <p class="info-text"></p>
                        </div>
                    </div>
                    <div class="info-item-content">
                        <div class="main-title">
                            <h3 class="title">
                                <span class="font-4">Travel</span>Packages
                            </h3>
                            <div class="price"><span></span></div>
                            <a href="#" class="button">Details</a>
                        </div>
                    </div>
                </div>
                <div class="slider-info-item">
                    <div class="info-item-media">
                        <img src="assets/img/american-visa-document.jpg" data-at2x="assets/img/american-visa-document.jpg" alt="">
                        <div class="info-item-text">
                            <div class="info-price font-4"><span></span></div>
                            <div class="info-temp font-4"><span></span></div>
                            <p class="info-text"></p>
                        </div>
                    </div>
                    <div class="info-item-content">
                        <div class="main-title">
                            <h3 class="title">
                                <span class="font-4">Visa</span> Processing
                            </h3>
                            <div class="price"><span></span></div>
                            <a href="#" class="button">Details</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<!--- About Us Section --->
<div class="py-20 bg-white">
    <div class="container m-auto px-6 text-gray-800 md:px-12 xl:px-6">
        <div class="space-y-6 md:space-y-0 md:flex md:gap-6 lg:items-center lg:gap-12">
            <div class="md:5/12 lg:w-5/12">
                <img src="assets/images/logo.png" alt="Big Billboard" width="" height="">
            </div>
            <div class="md:7/12 lg:w-6/12">
                <h2 class="text-lg font-bold text-sky-500 uppercase">Get to Know Us</h2>
                <h2 class="text-2xl font-bold md:text-4xl"><span class="text-sky-500">AL-SOMU</span> TRAVEL AGENCY</h2>
                <p class="mt-6 font-medium">Looking for a company that specializes in travel and tourism services? Look no further than our team, dedicated to meeting the desires of customers in collaboration with our distinguished partners.
                </p>

                <div class="divide-y divide-sky-600">
                    <p class="mt-4 font-medium pb-4">Our mission is to provide a unique experience to every customer, with secure reservations and competitive prices that suit the needs of both individuals and companies. Trust us to deliver the best travel experience possible!
                    </p>
                    <h2 class="text-lg font-medium text-gray-500pt-4">Bashaier Othman</h2>
                </div>


            </div>
        </div>
    </div>
</div>



<!-- Places Slider Section -->
<main class="min-h-screen bg-white flex items-center justify-center" x-data="carouselFilter()">
    <div class="container grid grid-cols-1">

        <div class="row-start-2 col-start-1" x-show="active == 0" x-transition:enter="transition ease-out duration-300" x-transition:enter-start="opacity-0 transform scale-90" x-transition:enter-end="opacity-100 transform scale-100" x-transition:leave="transition ease-in duration-300" x-transition:leave-start="opacity-100 transform scale-100" x-transition:leave-end="opacity-0 transform scale-90">
            <div class="grid grid-cols-1 grid-rows-1" x-data="carousel()" x-init="init()">
                <div class="col-start-1 row-start-1 relative z-20 flex items-center justify-center pointer-events-none">

                    <h1 class="absolute text-5xl uppercase font-black tracking-widest" x-show="active == 0" x-transition:enter="transition ease-out duration-300" x-transition:enter-start="opacity-0 transform translate-y-12" x-transition:enter-end="opacity-100 transform translate-y-0" x-transition:leave="transition ease-out duration-300" x-transition:leave-start="opacity-100 transform translate-y-0" x-transition:leave-end="opacity-0 transform -translate-y-12">London, United Kingdom</h1>
                    <h1 class="absolute text-5xl uppercase font-black tracking-widest" x-show="active == 1" x-transition:enter="transition ease-out duration-300" x-transition:enter-start="opacity-0 transform translate-y-12" x-transition:enter-end="opacity-100 transform translate-y-0" x-transition:leave="transition ease-out duration-300" x-transition:leave-start="opacity-100 transform translate-y-0" x-transition:leave-end="opacity-0 transform -translate-y-12">Paris, France</h1>
                    <h1 class="absolute text-5xl uppercase font-black tracking-widest" x-show="active == 2" x-transition:enter="transition ease-out duration-300" x-transition:enter-start="opacity-0 transform translate-y-12" x-transition:enter-end="opacity-100 transform translate-y-0" x-transition:leave="transition ease-out duration-300" x-transition:leave-start="opacity-100 transform translate-y-0" x-transition:leave-end="opacity-0 transform -translate-y-12">Santorini, Greece</h1>
                    <h1 class="absolute text-5xl uppercase font-black tracking-widest" x-show="active == 3" x-transition:enter="transition ease-out duration-300" x-transition:enter-start="opacity-0 transform translate-y-12" x-transition:enter-end="opacity-100 transform translate-y-0" x-transition:leave="transition ease-out duration-300" x-transition:leave-start="opacity-100 transform translate-y-0" x-transition:leave-end="opacity-0 transform -translate-y-12">Barcelona, Spain</h1>
                    <h1 class="absolute text-5xl uppercase font-black tracking-widest" x-show="active == 4" x-transition:enter="transition ease-out duration-300" x-transition:enter-start="opacity-0 transform translate-y-12" x-transition:enter-end="opacity-100 transform translate-y-0" x-transition:leave="transition ease-out duration-300" x-transition:leave-start="opacity-100 transform translate-y-0" x-transition:leave-end="opacity-0 transform -translate-y-12">Milan, Italy</h1>
                    <h1 class="absolute text-5xl uppercase font-black tracking-widest" x-show="active == 5" x-transition:enter="transition ease-out duration-300" x-transition:enter-start="opacity-0 transform translate-y-12" x-transition:enter-end="opacity-100 transform translate-y-0" x-transition:leave="transition ease-out duration-300" x-transition:leave-start="opacity-100 transform translate-y-0" x-transition:leave-end="opacity-0 transform -translate-y-12">Istanbul, Turkey</h1>
                    <h1 class="absolute text-5xl uppercase font-black tracking-widest" x-show="active == 6" x-transition:enter="transition ease-out duration-300" x-transition:enter-start="opacity-0 transform translate-y-12" x-transition:enter-end="opacity-100 transform translate-y-0" x-transition:leave="transition ease-out duration-300" x-transition:leave-start="opacity-100 transform translate-y-0" x-transition:leave-end="opacity-0 transform -translate-y-12">Lisbon, Portugal</h1>
                    <h1 class="absolute text-5xl uppercase font-black tracking-widest" x-show="active == 7" x-transition:enter="transition ease-out duration-300" x-transition:enter-start="opacity-0 transform translate-y-12" x-transition:enter-end="opacity-100 transform translate-y-0" x-transition:leave="transition ease-out duration-300" x-transition:leave-start="opacity-100 transform translate-y-0" x-transition:leave-end="opacity-0 transform -translate-y-12">Zurich, Switzerland</h1>
                </div>


                <div class="carousel col-start-1 row-start-1" x-ref="carousel">
                    <div class="w-3/5 px-2">
                        <img src="storage/united kingdom.jpg" loading="lazy">
                    </div>
                    <div class="w-3/5 px-2">
                        <img src="storage/greece.jpg" loading="lazy">
                    </div>
                    <div class="w-3/5 px-2">
                        <img src="storage/greece.jpg" loading="lazy">
                    </div>
                    <div class="w-3/5 px-2">
                        <img src="storage/spain.jpg" loading="lazy">
                    </div>
                    <div class="w-3/5 px-2">
                        <img src="storage/italy.jpg" loading="lazy">
                    </div>
                    <div class="w-3/5 px-2">
                        <img src="storage/turkey.jpg" loading="lazy">
                    </div>
                    <div class="w-3/5 px-2">
                        <img src="storage/portugal.jpg" loading="lazy">
                    </div>
                    <div class="w-3/5 px-2">
                        <img src="storage/switzerland.jpg" loading="lazy">
                    </div>
                </div>
            </div>
        </div>



    </div>
</main>
<script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>
<script defer>
    function carousel() {
        return {
            active: 0,
            init() {
                var flkty = new Flickity(this.$refs.carousel, {
                    wrapAround: true
                });
                flkty.on('change', i => this.active = i);
            }
        }
    }

    function carouselFilter() {
        return {
            active: 0,
            changeActive(i) {
                this.active = i;

                this.$nextTick(() => {
                    let flkty = Flickity.data(this.$el.querySelectorAll('.carousel')[i]);
                    flkty.resize();

                    console.log(flkty);
                });
            }
        }
    }
</script>







<!--- Newsletter Section -->
<div class="relative isolate overflow-hidden bg-sky-800 py-16 sm:py-24 lg:py-32">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
        <div class="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-2">
            <div class="max-w-xl lg:max-w-lg">
                <h2 class="text-3xl font-bold tracking-tight text-white sm:text-4xl">Subscribe to our newsletter.</h2>
                <p class="mt-4 text-lg leading-8 text-gray-300">Subscribe to our newsletter to get the latest travel deals and vacation booking discounts. We'll send you exclusive offers and promotions straight to your inbox, along with helpful travel tips and destination recommendations.</p>
                <div class="mt-6 flex max-w-md gap-x-4">
                    <label for="email-address" class="sr-only">Email address</label>
                    <input id="email-address" name="email" type="email" autocomplete="email" required class="min-w-0 flex-auto rounded-md border-0 bg-white/5 px-3.5 py-2 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6" placeholder="Enter your email">
                    <button type="submit" class="flex-none rounded-md bg-indigo-500 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">Subscribe</button>
                </div>
            </div>
            <dl class="grid grid-cols-1 gap-x-8 gap-y-10 sm:grid-cols-2 lg:pt-2">
                <div class="flex flex-col items-start">
                    <div class="rounded-md bg-white/5 p-2 ring-1 ring-white/10">
                        <svg class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5m-9-6h.008v.008H12v-.008zM12 15h.008v.008H12V15zm0 2.25h.008v.008H12v-.008zM9.75 15h.008v.008H9.75V15zm0 2.25h.008v.008H9.75v-.008zM7.5 15h.008v.008H7.5V15zm0 2.25h.008v.008H7.5v-.008zm6.75-4.5h.008v.008h-.008v-.008zm0 2.25h.008v.008h-.008V15zm0 2.25h.008v.008h-.008v-.008zm2.25-4.5h.008v.008H16.5v-.008zm0 2.25h.008v.008H16.5V15z" />
                        </svg>
                    </div>
                    <dt class="mt-4 font-semibold text-white">Weekly articles</dt>
                    <dd class="mt-2 leading-7 text-gray-200">From tips on how to travel sustainably to guides on the best hidden gems to visit in popular tourist destinations, our articles aim to inspire and educate our readers</dd>
                </div>
                <div class="flex flex-col items-start">
                    <div class="rounded-md bg-white/5 p-2 ring-1 ring-white/10">
                        <svg class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M10.05 4.575a1.575 1.575 0 10-3.15 0v3m3.15-3v-1.5a1.575 1.575 0 013.15 0v1.5m-3.15 0l.075 5.925m3.075.75V4.575m0 0a1.575 1.575 0 013.15 0V15M6.9 7.575a1.575 1.575 0 10-3.15 0v8.175a6.75 6.75 0 006.75 6.75h2.018a5.25 5.25 0 003.712-1.538l1.732-1.732a5.25 5.25 0 001.538-3.712l.003-2.024a.668.668 0 01.198-.471 1.575 1.575 0 10-2.228-2.228 3.818 3.818 0 00-1.12 2.687M6.9 7.575V12m6.27 4.318A4.49 4.49 0 0116.35 15m.002 0h-.002" />
                        </svg>
                    </div>
                    <dt class="mt-4 font-semibold text-white">No spam</dt>
                    <dd class="mt-2 leading-7 text-gray-200">We only send emails that we believe will be of interest to you, such as travel deals, vacation booking discounts, and informative articles. We also promise not to share your email address with any third-party companies</dd>
                </div>
            </dl>
        </div>
    </div>
    <div class="absolute left-1/2 top-0 -z-10 -translate-x-1/2 blur-3xl xl:-top-6" aria-hidden="true">
        <div class="aspect-[1155/678] w-[72.1875rem] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
</div>