<style>
    .flickity-viewport {
        height: 500px !important;
    }

    .video-docker video {
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    .video-docker::after {
        content: "";
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        left: 0;
        background: rgba(0, 0, 0, 0.6);
        z-index: 1;
    }

    .video-content {
        z-index: 2;
    }
</style>
<section class="relative h-screen flex flex-col items-center justify-center text-center text-white py-0 px-3">
    <div class="absolute top-0 left-0 w-full h-full overflow-hidden">
        <video class="min-w-full min-h-full absolute object-cover" src="storage/home_playback.mp4" type="video/mp4" autoplay muted loop></video>
    </div>
    <div class="video-content space-y-2">
        <div class="absolute bottom-0 left-0 w-full">
            <div class="flex">
                <div class="grid grid-cols-4 w-full" id="slider-grid">
                    <div class="relative h-48 cursor-pointer overflow-hidden translate-y-28 transition-all duration-800s hover:translate-y-0">
                        <div class="absolute inset-0 flex flex-col p-6 text-center text-white bg-gradient-to-b from-black to-transparent ">
                            <h2 class="Montserrat text-start text-md font-bold">Hotel</h2>
                            <h2 class="Hind text-start text-2xl font-bold">Reservation</h2>
                        </div>
                        <img src="assets/images/luxury-classic-modern-bedroom-suite-hotel.jpg" alt="Card 1" class="w-full h-full object-cover transition-all duration-500 hover:translate-y-full">
                    </div>
                    <div class="relative h-48 cursor-pointer overflow-hidden translate-y-28 transition-all duration-800s hover:translate-y-0">
                        <div class="absolute inset-0 flex flex-col p-6 text-center text-white bg-gradient-to-b from-black to-transparent ">
                            <h2 class="Montserrat text-start text-md font-bold">Car</h2>
                            <h2 class="Hind text-start text-2xl font-bold">Booking</h2>
                        </div>
                        <img src="assets/images/stylish-elegant-woman-car-salon.jpg" alt="Card 2" class="w-full h-full object-cover transition-all duration-500 hover:translate-y-full">
                    </div>
                    <div class="relative h-48 cursor-pointer overflow-hidden translate-y-28 transition-all duration-800s hover:translate-y-0">
                        <div class="absolute inset-0 flex flex-col p-6 text-center text-white bg-gradient-to-b from-black to-transparent ">
                            <h2 class="Montserrat text-start text-md font-bold">Travel</h2>
                            <h2 class="Hind text-start text-2xl font-bold">Packages</h2>
                        </div>
                        <img src="assets/images/james-bond-islands-in-thailand-2022-11-10-17-55-09-utc.jpg" alt="Card 3" class="w-full h-full object-cover transition-all duration-500 hover:translate-y-full">
                    </div>
                    <div class="relative h-48 cursor-pointer overflow-hidden translate-y-28 transition-all duration-800s hover:translate-y-0">
                        <div class="absolute inset-0 flex flex-col p-6 text-center text-white bg-gradient-to-b from-black to-transparent ">
                            <h2 class="Montserrat text-start text-md font-bold">Visa</h2>
                            <h2 class="Hind text-start text-2xl font-bold">Processing</h2>
                        </div>
                        <img src="assets/images/american-visa-document.jpg" alt="Card 4" class="w-full h-full object-cover transition-all duration-500 hover:translate-y-full">
                    </div>
                </div>
            </div>

        </div>

    </div>
</section>
<script>
    const slider_grid = document.querySelector("#slider-grid")
</script>


<!--- About Us Section --->
<section class="relative py-20 bg-white z-30" id="About-us">
    <div class="container m-auto px-6 text-gray-800 md:px-12 xl:px-6">
        <div class="space-y-6 md:space-y-0 md:flex md:gap-6 lg:items-center lg:gap-12">

            <div class="my-8 mx-12 md:7/12 lg:w-6/12">
                <h2 class="Montserrat text-lg font-bold text-sky-500 uppercase">Get to Know Us</h2>
                <h2 class="Hind text-2xl font-bold md:text-4xl"><span class="text-sky-500">AL-SOMU</span> TRAVEL AGENCY</h2>
                <p class="Hind mt-6 font-medium">Looking for a company that specializes in travel and tourism services? Look no further than our team, dedicated to meeting the desires of customers in collaboration with our distinguished partners.
                </p>

                <div class="divide-y divide-sky-600">
                    <p class="Hind mt-4 font-medium pb-4">Our mission is to provide a unique experience to every customer, with secure reservations and competitive prices that suit the needs of both individuals and companies. Trust us to deliver the best travel experience possible!
                    </p>
                    <h2 class="Parisienne text-3xl font-medium text-gray-500 pt-4">Bashaier Othman</h2>
                </div>
            </div>
        </div>
    </div>
</section>



<!-- Places Slider Section -->
<div class="flex mb-10 items-center justify-center bg-white">

    <div class="grid md:grid-cols-4 sm:grid-rows-1">

        <!-- Card 1 -->
        <div class="sm:w-full relative">
            <div class="absolute rounded-md w-full inset-0 bg-gradient-to-t from-black to-transparent">
            </div>
            <div>
                <div class="absolute bottom-0 left-0 p-6">
                    <h2 class="Montserrat text-xs text-sky-400">LONDON</h2>
                    <p class="Hind text-lg font-semibold leading-4 text-white mt-2">UNITED KINGDOM</p>
                </div>
            </div>
            <img src="storage/united kingdom.jpg" class="w-full" alt="chair">
        </div>

        <!-- Card 2 -->
        <div class="sm:w-full relative">
            <div class="absolute rounded-md w-full inset-0 bg-gradient-to-t from-black to-transparent">
            </div>
            <div>
                <div class="absolute bottom-0 left-0 p-6">
                    <h2 class="Montserrat text-xs text-sky-400">PARIS</h2>
                    <p class="Hind text-lg font-semibold leading-4 text-white mt-2">FRANCE</p>
                </div>
            </div>
            <img src="storage/france.jpg" class="w-full" alt="chair">
        </div>

        <!-- Card 3 -->
        <div class="sm:w-full relative">
            <div class="absolute rounded-md w-full inset-0 bg-gradient-to-t from-black to-transparent">
            </div>
            <div>
                <div class="absolute bottom-0 left-0 p-6">
                    <h2 class="Montserrat text-xs text-sky-400">SANTORINI</h2>
                    <p class="Hind text-lg font-semibold leading-4 text-white mt-2">GREECE</p>
                </div>
            </div>
            <img src="storage/greece.jpg" class="w-full" alt="chair">
        </div>

        <!-- Card 4 -->
        <div class="sm:w-full relative">
            <div class="absolute rounded-md w-full inset-0 bg-gradient-to-t from-black to-transparent">
            </div>
            <div>
                <div class="absolute bottom-0 left-0 p-6">
                    <h2 class="Montserrat text-xs text-sky-400">BARCELONA</h2>
                    <p class="Hind text-lg font-semibold leading-4 text-white mt-2">SPAIN</p>
                </div>
            </div>
            <img src="storage/spain.jpg" class="w-full" alt="chair">
        </div>

        <!-- Card 5 -->
        <div class="sm:w-full relative">
            <div class="absolute rounded-md w-full inset-0 bg-gradient-to-t from-black to-transparent">
            </div>
            <div>
                <div class="absolute bottom-0 left-0 p-6">
                    <h2 class="Montserrat text-xs text-sky-400">MILAN</h2>
                    <p class="Hind text-lg font-semibold leading-4 text-white mt-2">ITALY</p>
                </div>
            </div>
            <img src="storage/italy.jpg" class="w-full" alt="chair">
        </div>

        <!-- Card 6 -->
        <div class="sm:w-full relative">
            <div class="absolute rounded-md w-full inset-0 bg-gradient-to-t from-black to-transparent">
            </div>
            <div>
                <div class="absolute bottom-0 left-0 p-6">
                    <h2 class="Montserrat text-xs text-sky-400">TURKEY</h2>
                    <p class="Hind text-lg font-semibold leading-4 text-white mt-2">ISTANBUL</p>
                </div>
            </div>
            <img src="storage/turkey.jpg" class="w-full" alt="chair">
        </div>

        <!-- Card 7 -->
        <div class="sm:w-full relative">
            <div class="absolute rounded-md w-full inset-0 bg-gradient-to-t from-black to-transparent">
            </div>
            <div>
                <div class="absolute bottom-0 left-0 p-6">
                    <h2 class="Montserrat text-xs text-sky-400">LISBON</h2>
                    <p class="Hind text-lg font-semibold leading-4 text-white mt-2">PORTUGAL</p>
                </div>
            </div>
            <img src="storage/portugal.jpg" class="w-full" alt="chair">
        </div>

        <!-- Card 8 -->
        <div class="sm:w-full relative">
            <div class="absolute rounded-md w-full inset-0 bg-gradient-to-t from-black to-transparent">
            </div>
            <div>
                <div class="absolute bottom-0 left-0 p-6">
                    <h2 class="Montserrat text-xs text-sky-400">ZURICH</h2>
                    <p class="Hind text-lg font-semibold leading-4 text-white mt-2">SWITZERLAND</p>
                </div>
            </div>
            <img src="storage/switzerland.jpg" class="w-full" alt="chair">
        </div>

    </div>

</div>




<!-- Stats -->
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-wrap -m-4 text-center divide-x divide-sky-600">
            <div class="p-4 sm:w-1/5 w-1/2 flex items-center justify-center">
                <div class="text-gray-700 text-5xl">
                    <i class="counter-icon flaticon-suntour-world"></i>
                </div>
                <div class="pt-4 px-2">
                    <h2 class="Hind title-font font-medium sm:text-4xl text-3xl text-gray-800">
                        <div data-count="345" class="counter">0</div>
                    </h2>
                    <p class="Montserrat leading-relaxed text-gray-400">Tours</p>
                </div>
            </div>
            <div class="p-4 sm:w-1/5 w-1/2 flex items-center justify-center">
                <div class="text-gray-700 text-5xl">
                    <i class="counter-icon flaticon-suntour-fireworks"></i>
                </div>
                <div class=" pt-4 px-2">
                    <h2 class="Hind title-font font-medium sm:text-4xl text-3xl text-gray-800">
                        <div data-count="438" class="counter">0</div>
                    </h2>
                    <p class="Montserrat leading-relaxed text-gray-400">Holidays</p>
                </div>
            </div>
            <div class="p-4 sm:w-1/5 w-1/2 flex items-center justify-center">
                <div class="text-gray-700 text-5xl">
                    <i class="counter-icon flaticon-suntour-hotel"></i>
                </div>
                <div class="pt-4 px-2">
                    <h2 class="Hind title-font font-medium sm:text-4xl text-3xl text-gray-800">
                        <div data-count="526" class="counter">0</div>
                    </h2>
                    <p class="Montserrat leading-relaxed text-gray-400">Hotels</p>
                </div>
            </div>
            <div class="p-4 sm:w-1/5 w-1/2 flex items-center justify-center">
                <div class="text-gray-700 text-5xl">
                    <i class="counter-icon flaticon-suntour-airplane"></i>
                </div>
                <div class="pt-4 px-2">
                    <h2 class="Hind title-font font-medium sm:text-4xl text-3xl text-gray-800">
                        <div data-count="293" class="counter">0</div>
                    </h2>
                    <p class="Montserrat leading-relaxed text-gray-400">Flights</p>
                </div>
            </div>
            <div class="p-4 sm:w-1/5 w-1/2 flex items-center justify-center">
                <div class="text-gray-700 text-5xl">
                    <i class="counter-icon flaticon-suntour-car"></i>
                </div>
                <div class="pt-4 px-2">
                    <h2 class="Hind title-font font-medium sm:text-4xl text-3xl text-gray-800">
                        <div data-count="675" class="counter">0</div>
                    </h2>
                    <p class="Montserrat leading-relaxed text-gray-400">Cars</p>
                </div>
            </div>
        </div>
    </div>
</section>
<script type="text/javascript" src="assets/vendor/jquery.min.js"></script>
<script defer>
    var is_count = true;

    function counter() {
        if ($(".counter").length) {
            var winScr = $(window).scrollTop();
            var winHeight = $(window).height();
            var ofs = $(".counter").offset().top;

            $(window).on("scroll", function() {
                winScr = $(window).scrollTop();
                winHeight = $(window).height();
                ofs = $(".counter").offset().top;

                if (winScr + winHeight > ofs && is_count) {
                    $(".counter").each(function() {
                        var atr = $(this).attr("data-count");
                        var item = $(this);
                        var n = atr;
                        var d = 0;
                        var c;

                        item.text(d);
                        var interval = setInterval(function() {
                            c = atr / 70;
                            d += c;
                            if (atr - d < c) {
                                d = atr;
                            }
                            item.text(Math.floor(d));
                            if (d == atr) {
                                clearInterval(interval);
                            }
                        }, 50);
                    });
                    is_count = false;
                }
            });
        }
    }
</script>


<!--- Newsletter Section -->
<div class="relative isolate overflow-hidden bg-sky-800 py-16 sm:py-24 lg:py-32">
    <div class="mx-auto max-w-7xl px-6 lg:px-8">
        <div class="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-2">
            <div class="max-w-xl lg:max-w-lg">
                <h2 class="Montserrat text-3xl font-bold tracking-tight text-white sm:text-4xl">Subscribe to our newsletter.</h2>
                <p class="Hind mt-4 text-lg leading-8 text-gray-300">Subscribe to our newsletter to get the latest travel deals and vacation booking discounts. We'll send you exclusive offers and promotions straight to your inbox, along with helpful travel tips and destination recommendations.</p>
                <form class="mt-6 flex max-w-md gap-x-4" id="newsForm">
                    <label for="email" class="Hind sr-only">Email address</label>
                    <input id="email" name="email" type="email" autocomplete="email" required class="min-w-0 flex-auto rounded-md border-0 bg-white/5 px-3.5 py-2 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6" placeholder="Enter your email">
                    <button type="submit" class="Hind flex-none rounded-md bg-indigo-500 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">Subscribe</button>
                </form>
            </div>
            <dl class="grid grid-cols-1 gap-x-8 gap-y-10 sm:grid-cols-2 lg:pt-2">
                <div class="flex flex-col items-start">
                    <div class="rounded-md bg-white/5 p-2 ring-1 ring-white/10">
                        <svg class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5m-9-6h.008v.008H12v-.008zM12 15h.008v.008H12V15zm0 2.25h.008v.008H12v-.008zM9.75 15h.008v.008H9.75V15zm0 2.25h.008v.008H9.75v-.008zM7.5 15h.008v.008H7.5V15zm0 2.25h.008v.008H7.5v-.008zm6.75-4.5h.008v.008h-.008v-.008zm0 2.25h.008v.008h-.008V15zm0 2.25h.008v.008h-.008v-.008zm2.25-4.5h.008v.008H16.5v-.008zm0 2.25h.008v.008H16.5V15z" />
                        </svg>
                    </div>
                    <dt class="Montserrat mt-4 font-semibold text-white">Weekly articles</dt>
                    <dd class="Hind mt-2 leading-7 text-gray-200">From tips on how to travel sustainably to guides on the best hidden gems to visit in popular tourist destinations, our articles aim to inspire and educate our readers</dd>
                </div>
                <div class="flex flex-col items-start">
                    <div class="rounded-md bg-white/5 p-2 ring-1 ring-white/10">
                        <svg class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M10.05 4.575a1.575 1.575 0 10-3.15 0v3m3.15-3v-1.5a1.575 1.575 0 013.15 0v1.5m-3.15 0l.075 5.925m3.075.75V4.575m0 0a1.575 1.575 0 013.15 0V15M6.9 7.575a1.575 1.575 0 10-3.15 0v8.175a6.75 6.75 0 006.75 6.75h2.018a5.25 5.25 0 003.712-1.538l1.732-1.732a5.25 5.25 0 001.538-3.712l.003-2.024a.668.668 0 01.198-.471 1.575 1.575 0 10-2.228-2.228 3.818 3.818 0 00-1.12 2.687M6.9 7.575V12m6.27 4.318A4.49 4.49 0 0116.35 15m.002 0h-.002" />
                        </svg>
                    </div>
                    <dt class="Montserrat mt-4 font-semibold text-white">No spam</dt>
                    <dd class="Hind mt-2 leading-7 text-gray-200">We only send emails that we believe will be of interest to you, such as travel deals, vacation booking discounts, and informative articles. We also promise not to share your email address with any third-party companies</dd>
                </div>
            </dl>
        </div>
    </div>
    <div class="absolute left-1/2 top-0 -z-10 -translate-x-1/2 blur-3xl xl:-top-6" aria-hidden="true">
        <div class="aspect-[1155/678] w-[72.1875rem] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
</div>
<script src="assets/vendor/sweetalert2.min.js"></script>
<script defer>
    //"use strict"; // start of use strict

    $(document).ready(function() {
        counter();

        const newsForm = document.querySelector('#newsForm');
        newsForm.addEventListener("submit", (e) => {
            e.preventDefault();

            // handle submit
            const emailInput = document.querySelector('#email');
            const email = emailInput.value;

            let data = new FormData(newsForm);

            fetch("<?= DOMAIN ?>/post/newsletter", {
                    method: "POST",
                    body: data
                })

                // (C) RETURN SERVER RESPONSE AS TEXT
                .then(res => {
                    if (res.status != 200) {
                        throw new Error("Bad Server Response");
                    }
                    return res.text();
                })

                // (D) SERVER RESPONSE
                .then(res => {
                    responseVal = JSON.parse(res);
                    if (responseVal.is_errors === 1) {
                        console.log(responseVal.info);
                        Swal.fire({
                            icon: 'error',
                            title: 'Failed to Subscribe',
                            text: 'Something went wrong!, please try again.'
                        })
                    } else {
                        emailInput.value = '';
                        Swal.fire(
                            'Congratulation on your Subscription',
                            'You will receive our offers directly on your inbox.',
                            'success'
                        );
                    }
                })

                // (E) HANDLE ERRORS - OPTIONAL
                .catch(err => {
                    console.error(err);
                    Swal.fire({
                        icon: 'error',
                        title: 'Unable to Subscribe now',
                        text: 'We are having issue on our server, please try again lates'
                    })
                });
        });
    });
</script>