<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> <?= TITLE ?> </title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="assets/css/flaticon.css" />
    <link rel="stylesheet" href="assets/css/sweetalert2.min.css" />

    <style>
        @import url(https://fonts.googleapis.com/css?family=Montserrat:400);
        @import url(https://fonts.googleapis.com/css?family=Merriweather:400);
        @import url(https://fonts.googleapis.com/css?family=Roboto:400,500,600);
        @import url(https://fonts.googleapis.com/css?family=Hind+Siliguri:400,500,600);
        @import url(https://fonts.googleapis.com/css?family=Parisienne);

        .Hind {
            font-family: 'Hind Siliguri', 'sans-serif';
        }

        .Montserrat {
            font-family: 'Montserrat', 'sans-serif';
        }

        .Roboto {
            font-family: 'Roboto', 'sans-serif';
        }

        .Merriweather {
            font-family: 'Merriweather', 'sans-serif';
        }

        .Parisienne {
            font-family: 'Parisienne', 'sans-serif';
        }
    </style>
</head>

<body style="background: #edf2f7;">
    <div class="relative bg-gray-50 overflow-hidden">