<style>
	.sticky {
		background: #fff;
		color: black;
		position: fixed;
		width: 100%;
		padding: 10px 80px;
		top: 0;
		transition: all 0.4s ease;
		box-shadow: 0px 1px 15px rgb(0 0 0 / 10%);
		z-index: 999;
	}
</style>
<nav class="absolute w-screen mx-auto flex items-center justify-between p-6 lg:px-8 z-50 text-white" aria-label="Global" id="navbar">
	<div class="flex lg:flex-1">
		<a href="<?= DOMAIN ?>" class="-m-1.5 p-1.5">
			<span class="sr-only text-white">Al-Somu</span>
			<img class="h-16 w-auto" src="assets/images/logo.png" alt="">
		</a>
	</div>
	<div class="flex lg:hidden">
		<button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700" id="hamburgerBtn">
			<span class="sr-only">Open main menu</span>
			<svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
				<path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
			</svg>
		</button>
	</div>
	<div class="hidden lg:flex lg:gap-x-12">


		<a href="<?= DOMAIN ?>/home" class="text-sm font-semibold leading-6">Home</a>
		<a href="<?= DOMAIN ?>/about-us" class="text-sm font-semibold leading-6">About Us</a>

		<div class="relative">
			<button type="button" class="flex items-center gap-x-1 text-sm font-semibold leading-6" aria-expanded="false" id="dropdownBtn">
				Services
				<svg class="h-5 w-5 flex-none text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
					<path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
				</svg>
			</button>
			<div class="absolute -left-8 top-full z-10 mt-3 w-screen max-w-md overflow-hidden rounded-3xl bg-white shadow-lg ring-1 ring-gray-900/5 hidden" id="megaMenu">
				<div class="p-4">
					<div class="group relative flex items-center gap-x-6 rounded-lg p-4 text-sm leading-6 hover:bg-gray-50">
						<div class="flex h-11 w-11 flex-none items-center justify-center rounded-lg bg-gray-50 group-hover:bg-white">
							<svg class="h-6 w-6 text-gray-600 group-hover:text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
								<path stroke-linecap="round" stroke-linejoin="round" d="M10.125 2.25h-4.5c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125v-9M10.125 2.25h.375a9 9 0 019 9v.375M10.125 2.25A3.375 3.375 0 0113.5 5.625v1.5c0 .621.504 1.125 1.125 1.125h1.5a3.375 3.375 0 013.375 3.375M9 15l2.25 2.25L15 12" />
							</svg>
						</div>
						<div class="flex-auto">
							<a href="<?= DOMAIN ?>/services/uk-schengen-visa" class="block font-semibold text-gray-900">
								UK AND SCHENGEN VISA
								<span class="absolute inset-0"></span>
							</a>
							<p class="mt-1 text-gray-600">Apply for UK and Schengen Visa</p>
						</div>
					</div>
					<div class="group relative flex items-center gap-x-6 rounded-lg p-4 text-sm leading-6 hover:bg-gray-50">
						<div class="flex h-11 w-11 flex-none items-center justify-center rounded-lg bg-gray-50 group-hover:bg-white">
							<svg class="h-6 w-6 text-gray-600 group-hover:text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
								<path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
							</svg>
						</div>
						<div class="flex-auto">
							<a href="<?= DOMAIN ?>/services/usa-visa" class="block font-semibold text-gray-900">
								USA VISA
								<span class="absolute inset-0"></span>
							</a>
							<p class="mt-1 text-gray-600">Apply for USA Visa</p>
						</div>
					</div>
					<div class="group relative flex items-center gap-x-6 rounded-lg p-4 text-sm leading-6 hover:bg-gray-50">
						<div class="flex h-11 w-11 flex-none items-center justify-center rounded-lg bg-gray-50 group-hover:bg-white">
							<svg class="w-6 h-6 text-gray-600 group-hover:text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
								<path stroke-linecap="round" stroke-linejoin="round" d="M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.967 8.967 0 00-6 2.292m0-14.25v14.25" />
							</svg>

						</div>
						<div class="flex-auto">
							<a href="<?= DOMAIN ?>/services/general-visa" class="block font-semibold text-gray-900">
								GENERAL VISA
								<span class="absolute inset-0"></span>
							</a>
							<p class="mt-1 text-gray-600">General Visa Requirements</p>
						</div>
					</div>
					<div class="group relative flex items-center gap-x-6 rounded-lg p-4 text-sm leading-6 hover:bg-gray-50">
						<div class="flex h-11 w-11 flex-none items-center justify-center rounded-lg bg-gray-50 group-hover:bg-white">
							<svg class="w-6 h-6 text-gray-600 group-hover:text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
								<path stroke-linecap="round" stroke-linejoin="round" d="M2.25 21h19.5m-18-18v18m10.5-18v18m6-13.5V21M6.75 6.75h.75m-.75 3h.75m-.75 3h.75m3-6h.75m-.75 3h.75m-.75 3h.75M6.75 21v-3.375c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21M3 3h12m-.75 4.5H21m-3.75 3.75h.008v.008h-.008v-.008zm0 3h.008v.008h-.008v-.008zm0 3h.008v.008h-.008v-.008z" />
							</svg>
						</div>
						<div class="flex-auto">
							<a href="<?= DOMAIN ?>/services/hotel-booking" class="block font-semibold text-gray-900">
								HOTEL BOOKINGS
								<span class="absolute inset-0"></span>
							</a>
							<p class="mt-1 text-gray-600">Booking your Hotel easly</p>
						</div>
					</div>
					<div class="group relative flex items-center gap-x-6 rounded-lg p-4 text-sm leading-6 hover:bg-gray-50">
						<div class="flex h-11 w-11 flex-none items-center justify-center rounded-lg bg-gray-50 group-hover:bg-white">
							<svg class="h-6 w-6 text-gray-600 group-hover:text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
								<path stroke-linecap="round" stroke-linejoin="round" d="M8.25 18.75a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h6m-9 0H3.375a1.125 1.125 0 01-1.125-1.125V14.25m17.25 4.5a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m3 0h1.125c.621 0 1.129-.504 1.09-1.124a17.902 17.902 0 00-3.213-9.193 2.056 2.056 0 00-1.58-.86H14.25M16.5 18.75h-2.25m0-11.177v-.958c0-.568-.422-1.048-.987-1.106a48.554 48.554 0 00-10.026 0 1.106 1.106 0 00-.987 1.106v7.635m12-6.677v6.677m0 4.5v-4.5m0 0h-12" />
							</svg>
						</div>
						<div class="flex-auto">
							<a href="<?= DOMAIN ?>/services/transportation" class="block font-semibold text-gray-900">
								TRANSPORTATION BOOKINGS
								<span class="absolute inset-0"></span>
							</a>
							<p class="mt-1 text-gray-600">We have Transportation service for you to use</p>
						</div>
					</div>
					<div class="group relative flex items-center gap-x-6 rounded-lg p-4 text-sm leading-6 hover:bg-gray-50">
						<div class="flex h-11 w-11 flex-none items-center justify-center rounded-lg bg-gray-50 group-hover:bg-white">
							<svg class="h-6 w-6 text-gray-600 group-hover:text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
								<path stroke-linecap="round" stroke-linejoin="round" d="M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5M10 11.25h4M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
							</svg>
						</div>
						<div class="flex-auto">
							<a href="<?= DOMAIN ?>/services/packages" class="block font-semibold text-gray-900">
								TRAVEL PACKAGES
								<span class="absolute inset-0"></span>
							</a>
							<p class="mt-1 text-gray-600">Choose one of our unique package for your travel</p>
						</div>
					</div>
				</div>

			</div>
		</div>


		<a href="<?= DOMAIN ?>/patrners" class="text-sm font-semibold leading-6">Our Partners</a>
	</div>
	<div class="hidden lg:flex lg:flex-1 lg:justify-end">
		<a href="<?= DOMAIN ?>/contact-us" class="text-sm font-semibold leading-6">Contact Us <span aria-hidden="true">&rarr;</span></a>
	</div>
</nav>
<!-- Mobile menu, show/hide based on menu open state. -->
<div class="hidden" role="dialog" aria-modal="true" id="mobileNavbar">
	<!-- Background backdrop, show/hide based on slide-over state. -->
	<div class="fixed inset-0 z-10"></div>
	<div class="fixed inset-y-0 right-0 z-10 w-full overflow-y-auto bg-white px-6 py-20 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">

		<div class="mt-6 flow-root">
			<div class="-my-6 divide-y divide-gray-500/10">
				<div class="space-y-2 py-6">
					<a href="<?= DOMAIN ?>/home" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Home</a>
					<a href="<?= DOMAIN ?>/about-us" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">About Us</a>
					<div class="-mx-3">
						<button type="button" class="flex w-full items-center justify-between rounded-lg py-2 pl-3 pr-3.5 text-base font-semibold leading-7 hover:bg-gray-50" aria-controls="disclosure-1" aria-expanded="false" id="mobileExpandBtn">
							Services
							<svg class="h-5 w-5 flex-none" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
								<path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
							</svg>
						</button>
						<!-- 'Product' sub-menu, show/hide based on menu state. -->
						<div class="mt-2 space-y-2 hidden" id="mobileExpandMenu">
							<a href="<?= DOMAIN ?>/services/uk-schengen-visa" class="block rounded-lg py-2 pl-6 pr-3 text-sm font-semibold leading-7 text-gray-900 hover:bg-gray-50">UK AND SCHENGEN VISA</a>
							<a href="<?= DOMAIN ?>/services/usa-visa" class="block rounded-lg py-2 pl-6 pr-3 text-sm font-semibold leading-7 text-gray-900 hover:bg-gray-50">USA VISA</a>
							<a href="<?= DOMAIN ?>/services/general-visa" class="block rounded-lg py-2 pl-6 pr-3 text-sm font-semibold leading-7 text-gray-900 hover:bg-gray-50">GENERAL VISA</a>
							<a href="<?= DOMAIN ?>/services/hotel-booking" class="block rounded-lg py-2 pl-6 pr-3 text-sm font-semibold leading-7 text-gray-900 hover:bg-gray-50">HOTEL BOOKINGS</a>
							<a href="<?= DOMAIN ?>/services/transportation" class="block rounded-lg py-2 pl-6 pr-3 text-sm font-semibold leading-7 text-gray-900 hover:bg-gray-50">TRANSPORTATION BOOKINGS</a>
							<a href="<?= DOMAIN ?>/services/packages" class="block rounded-lg py-2 pl-6 pr-3 text-sm font-semibold leading-7 text-gray-900 hover:bg-gray-50">TRAVEL PACKAGES</a>
						</div>
					</div>
					<a href="<?= DOMAIN ?>/partners" class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Our Partners</a>
				</div>
				<div class="py-6">
					<a href="<?= DOMAIN ?>/contact-us" class="-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">Contact Us</a>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	const hamburgerBtn = document.querySelector('#hamburgerBtn');
	const mobileNavbar = document.querySelector('#mobileNavbar');
	const megaMenu = document.querySelector('#megaMenu');
	const dropdownBtn = document.querySelector('#dropdownBtn');
	const mobileExpandMenu = document.querySelector('#mobileExpandMenu');
	const mobileExpandBtn = document.querySelector('#mobileExpandBtn');
	dropdownBtn.onclick = function() {
		megaMenu.classList.toggle('hidden');
	};

	hamburgerBtn.onclick = function() {
		mobileNavbar.classList.toggle('hidden');
	};

	mobileExpandBtn.onclick = function() {
		mobileExpandMenu.classList.toggle('hidden');
	};



	window.addEventListener('scroll', function() {
		const navbar = document.querySelector('#navbar');
		navbar.classList.toggle("sticky", window.scrollY > 0);
	})
</script>